### ISSUE TITLE
Damn you, Catalina

### ISSUE THREAD

**Issue by jessicaschilling** [jessicaschilling/mirada-tangodj#92]
Need to accommodate Catalina replacing iTunes with Music app. May just be a matter of name-replacement stuff, but may dig deeper: see https://dougscripts.com/itunes/2019/06/catalina-public-beta/

**Comment by iccir** [comment]
From a quick glance:

`index.js`: `com.apple.iTunes.playerInfo` might have changed in the Music app. User-facing references to "iTunes".

`iTunes/nowPlayingInfo.js`: the tell target should be "Music"

Also documentation and directory structure changes.

**Comment by jessicaschilling** [comment]
Thanks! And yep; was playing around with this on my local, but not quite there yet :)

**Comment by iccir** [comment]
I figured, but I'm doing this in Embrace at the moment, so I might as well search Miranda for all the strings I change! :)
